name: Deploy Firebase

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: yarn global add firebase-tools
      - name: yarn install, build and deploy
        run: |
          yarn install
          yarn run build
          firebase deploy --token "$FIREBASE_TOKEN" --only hosting,firestore:rules,firestore:indexes,functions
        env:
          CI: true
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}