name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: yarn global add firebase-tools
      - name: Install Dependencies
        run: yarn install
      - name: Build Project
        run: yarn run build
      - name: Deploy Firebase Project
        uses: w9jds/firebase-action@develop
        with:
          args: deploy --only hosting,firestore:rules,firestore:indexes,functions
        env:
          CI: true
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}